/**
 * DSFinV-K v2.4 CSV column schema, mechanically generated from the
 * official reference index.xml (BZSt, 02_index.xml/index.xml inside the
 * spec archive at
 * https://www.bzst.de/SharedDocs/Downloads/DE/Aussenpruefung/dsfinv_k_v_2_4.zip).
 * Do not hand-edit column lists here -- regenerate from the vendored XML
 * if the spec version changes.
 */
export interface DsfinvkColumn {
  name: string;
  type: 'string' | 'numeric';
  maxLength: number | null;
}

export interface DsfinvkTable {
  file: string;
  tableName: string;
  columns: DsfinvkColumn[];
}

export const DSFINVK_SCHEMA: readonly DsfinvkTable[] = [
  {
    file: 'cashpointclosing.csv',
    tableName: 'Stamm_Abschluss',
    columns: [
      { name: 'Z_KASSE_ID', type: 'string', maxLength: 50 },
      { name: 'Z_ERSTELLUNG', type: 'string', maxLength: 30 },
      { name: 'Z_NR', type: 'numeric', maxLength: null },
      { name: 'Z_BUCHUNGSTAG', type: 'string', maxLength: 25 },
      { name: 'TAXONOMIE_VERSION', type: 'string', maxLength: 10 },
      { name: 'Z_START_ID', type: 'string', maxLength: 40 },
      { name: 'Z_ENDE_ID', type: 'string', maxLength: 40 },
      { name: 'NAME', type: 'string', maxLength: 60 },
      { name: 'STRASSE', type: 'string', maxLength: 60 },
      { name: 'PLZ', type: 'string', maxLength: 10 },
      { name: 'ORT', type: 'string', maxLength: 62 },
      { name: 'LAND', type: 'string', maxLength: 3 },
      { name: 'STNR', type: 'string', maxLength: 20 },
      { name: 'USTID', type: 'string', maxLength: 15 },
      { name: 'Z_SE_ZAHLUNGEN', type: 'numeric', maxLength: null },
      { name: 'Z_SE_BARZAHLUNGEN', type: 'numeric', maxLength: null },
    ],
  },
  {
    file: 'location.csv',
    tableName: 'Stamm_Orte',
    columns: [
      { name: 'Z_KASSE_ID', type: 'string', maxLength: 50 },
      { name: 'Z_ERSTELLUNG', type: 'string', maxLength: 30 },
      { name: 'Z_NR', type: 'numeric', maxLength: null },
      { name: 'LOC_NAME', type: 'string', maxLength: 60 },
      { name: 'LOC_STRASSE', type: 'string', maxLength: 60 },
      { name: 'LOC_PLZ', type: 'string', maxLength: 10 },
      { name: 'LOC_ORT', type: 'string', maxLength: 62 },
      { name: 'LOC_LAND', type: 'string', maxLength: 3 },
      { name: 'LOC_USTID', type: 'string', maxLength: 15 },
    ],
  },
  {
    file: 'cashregister.csv',
    tableName: 'Stamm_Kassen',
    columns: [
      { name: 'Z_KASSE_ID', type: 'string', maxLength: 50 },
      { name: 'Z_ERSTELLUNG', type: 'string', maxLength: 30 },
      { name: 'Z_NR', type: 'numeric', maxLength: null },
      { name: 'KASSE_BRAND', type: 'string', maxLength: 50 },
      { name: 'KASSE_MODELL', type: 'string', maxLength: 50 },
      { name: 'KASSE_SERIENNR', type: 'string', maxLength: 70 },
      { name: 'KASSE_SW_BRAND', type: 'string', maxLength: 50 },
      { name: 'KASSE_SW_VERSION', type: 'string', maxLength: 50 },
      { name: 'KASSE_BASISWAEH_CODE', type: 'string', maxLength: 3 },
      { name: 'KEINE_UST_ZUORDNUNG', type: 'string', maxLength: 1 },
    ],
  },
  {
    file: 'slaves.csv',
    tableName: 'Stamm_Terminals',
    columns: [
      { name: 'Z_KASSE_ID', type: 'string', maxLength: 50 },
      { name: 'Z_ERSTELLUNG', type: 'string', maxLength: 30 },
      { name: 'Z_NR', type: 'numeric', maxLength: null },
      { name: 'TERMINAL_ID', type: 'string', maxLength: 50 },
      { name: 'TERMINAL_BRAND', type: 'string', maxLength: 50 },
      { name: 'TERMINAL_MODELL', type: 'string', maxLength: 50 },
      { name: 'TERMINAL_SERIENNR', type: 'string', maxLength: 70 },
      { name: 'TERMINAL_SW_BRAND', type: 'string', maxLength: 50 },
      { name: 'TERMINAL_SW_VERSION', type: 'string', maxLength: 50 },
    ],
  },
  {
    file: 'pa.csv',
    tableName: 'Stamm_Agenturen',
    columns: [
      { name: 'Z_KASSE_ID', type: 'string', maxLength: 50 },
      { name: 'Z_ERSTELLUNG', type: 'string', maxLength: 30 },
      { name: 'Z_NR', type: 'numeric', maxLength: null },
      { name: 'AGENTUR_ID', type: 'numeric', maxLength: null },
      { name: 'AGENTUR_NAME', type: 'string', maxLength: 60 },
      { name: 'AGENTUR_STRASSE', type: 'string', maxLength: 60 },
      { name: 'AGENTUR_PLZ', type: 'string', maxLength: 10 },
      { name: 'AGENTUR_ORT', type: 'string', maxLength: 62 },
      { name: 'AGENTUR_LAND', type: 'string', maxLength: 3 },
      { name: 'AGENTUR_STNR', type: 'string', maxLength: 20 },
      { name: 'AGENTUR_USTID', type: 'string', maxLength: 15 },
    ],
  },
  {
    file: 'tse.csv',
    tableName: 'Stamm_TSE',
    columns: [
      { name: 'Z_KASSE_ID', type: 'string', maxLength: 50 },
      { name: 'Z_ERSTELLUNG', type: 'string', maxLength: 30 },
      { name: 'Z_NR', type: 'numeric', maxLength: null },
      { name: 'TSE_ID', type: 'numeric', maxLength: null },
      { name: 'TSE_SERIAL', type: 'string', maxLength: 68 },
      { name: 'TSE_SIG_ALGO', type: 'string', maxLength: 21 },
      { name: 'TSE_ZEITFORMAT', type: 'string', maxLength: 31 },
      { name: 'TSE_PD_ENCODING', type: 'string', maxLength: 5 },
      { name: 'TSE_PUBLIC_KEY', type: 'string', maxLength: 512 },
      { name: 'TSE_ZERTIFIKAT_I', type: 'string', maxLength: 1000 },
      { name: 'TSE_ZERTIFIKAT_II', type: 'string', maxLength: 1000 },
    ],
  },
  {
    file: 'vat.csv',
    tableName: 'Stamm_USt',
    columns: [
      { name: 'Z_KASSE_ID', type: 'string', maxLength: 50 },
      { name: 'Z_ERSTELLUNG', type: 'string', maxLength: 30 },
      { name: 'Z_NR', type: 'numeric', maxLength: null },
      { name: 'UST_SCHLUESSEL', type: 'numeric', maxLength: null },
      { name: 'UST_SATZ', type: 'numeric', maxLength: null },
      { name: 'UST_BESCHR', type: 'string', maxLength: 55 },
    ],
  },
  {
    file: 'businesscases.csv',
    tableName: 'Z_GV_Typ',
    columns: [
      { name: 'Z_KASSE_ID', type: 'string', maxLength: 50 },
      { name: 'Z_ERSTELLUNG', type: 'string', maxLength: 30 },
      { name: 'Z_NR', type: 'numeric', maxLength: null },
      { name: 'GV_TYP', type: 'string', maxLength: 30 },
      { name: 'GV_NAME', type: 'string', maxLength: 40 },
      { name: 'AGENTUR_ID', type: 'numeric', maxLength: null },
      { name: 'UST_SCHLUESSEL', type: 'numeric', maxLength: null },
      { name: 'Z_UMS_BRUTTO', type: 'numeric', maxLength: null },
      { name: 'Z_UMS_NETTO', type: 'numeric', maxLength: null },
      { name: 'Z_UST', type: 'numeric', maxLength: null },
    ],
  },
  {
    file: 'payment.csv',
    tableName: 'Z_Zahlart',
    columns: [
      { name: 'Z_KASSE_ID', type: 'string', maxLength: 50 },
      { name: 'Z_ERSTELLUNG', type: 'string', maxLength: 30 },
      { name: 'Z_NR', type: 'numeric', maxLength: null },
      { name: 'ZAHLART_TYP', type: 'string', maxLength: 25 },
      { name: 'ZAHLART_NAME', type: 'string', maxLength: 60 },
      { name: 'Z_ZAHLART_BETRAG', type: 'numeric', maxLength: null },
    ],
  },
  {
    file: 'cash_per_currency.csv',
    tableName: 'Z_Waehrungen',
    columns: [
      { name: 'Z_KASSE_ID', type: 'string', maxLength: 50 },
      { name: 'Z_ERSTELLUNG', type: 'string', maxLength: 30 },
      { name: 'Z_NR', type: 'numeric', maxLength: null },
      { name: 'ZAHLART_WAEH', type: 'string', maxLength: 3 },
      { name: 'ZAHLART_BETRAG_WAEH', type: 'numeric', maxLength: null },
    ],
  },
  {
    file: 'transactions.csv',
    tableName: 'Bonkopf',
    columns: [
      { name: 'Z_KASSE_ID', type: 'string', maxLength: 50 },
      { name: 'Z_ERSTELLUNG', type: 'string', maxLength: 30 },
      { name: 'Z_NR', type: 'numeric', maxLength: null },
      { name: 'BON_ID', type: 'string', maxLength: 40 },
      { name: 'BON_NR', type: 'numeric', maxLength: null },
      { name: 'BON_TYP', type: 'string', maxLength: 30 },
      { name: 'BON_NAME', type: 'string', maxLength: 60 },
      { name: 'TERMINAL_ID', type: 'string', maxLength: 50 },
      { name: 'BON_STORNO', type: 'string', maxLength: 1 },
      { name: 'BON_START', type: 'string', maxLength: 30 },
      { name: 'BON_ENDE', type: 'string', maxLength: 30 },
      { name: 'BEDIENER_ID', type: 'string', maxLength: 50 },
      { name: 'BEDIENER_NAME', type: 'string', maxLength: 50 },
      { name: 'UMS_BRUTTO', type: 'numeric', maxLength: null },
      { name: 'KUNDE_NAME', type: 'string', maxLength: 50 },
      { name: 'KUNDE_ID', type: 'string', maxLength: 50 },
      { name: 'KUNDE_TYP', type: 'string', maxLength: 50 },
      { name: 'KUNDE_STRASSE', type: 'string', maxLength: 60 },
      { name: 'KUNDE_PLZ', type: 'string', maxLength: 10 },
      { name: 'KUNDE_ORT', type: 'string', maxLength: 62 },
      { name: 'KUNDE_LAND', type: 'string', maxLength: 3 },
      { name: 'KUNDE_USTID', type: 'string', maxLength: 15 },
      { name: 'BON_NOTIZ', type: 'string', maxLength: 255 },
    ],
  },
  {
    file: 'datapayment.csv',
    tableName: 'Bonkopf_Zahlarten',
    columns: [
      { name: 'Z_KASSE_ID', type: 'string', maxLength: 50 },
      { name: 'Z_ERSTELLUNG', type: 'string', maxLength: 30 },
      { name: 'Z_NR', type: 'numeric', maxLength: null },
      { name: 'BON_ID', type: 'string', maxLength: 40 },
      { name: 'ZAHLART_TYP', type: 'string', maxLength: 25 },
      { name: 'ZAHLART_NAME', type: 'string', maxLength: 60 },
      { name: 'ZAHLWAEH_CODE', type: 'string', maxLength: 3 },
      { name: 'ZAHLWAEH_BETRAG', type: 'numeric', maxLength: null },
      { name: 'BASISWAEH_BETRAG', type: 'numeric', maxLength: null },
    ],
  },
  {
    file: 'lines.csv',
    tableName: 'Bonpos',
    columns: [
      { name: 'Z_KASSE_ID', type: 'string', maxLength: 50 },
      { name: 'Z_ERSTELLUNG', type: 'string', maxLength: 30 },
      { name: 'Z_NR', type: 'numeric', maxLength: null },
      { name: 'BON_ID', type: 'string', maxLength: 40 },
      { name: 'POS_ZEILE', type: 'string', maxLength: 50 },
      { name: 'GUTSCHEIN_NR', type: 'string', maxLength: 50 },
      { name: 'ARTIKELTEXT', type: 'string', maxLength: 255 },
      { name: 'POS_TERMINAL_ID', type: 'string', maxLength: 50 },
      { name: 'GV_TYP', type: 'string', maxLength: 30 },
      { name: 'GV_NAME', type: 'string', maxLength: 40 },
      { name: 'INHAUS', type: 'string', maxLength: 1 },
      { name: 'P_STORNO', type: 'string', maxLength: 1 },
      { name: 'AGENTUR_ID', type: 'numeric', maxLength: null },
      { name: 'ART_NR', type: 'string', maxLength: 50 },
      { name: 'GTIN', type: 'string', maxLength: 50 },
      { name: 'WARENGR_ID', type: 'string', maxLength: 40 },
      { name: 'WARENGR', type: 'string', maxLength: 50 },
      { name: 'MENGE', type: 'numeric', maxLength: null },
      { name: 'FAKTOR', type: 'numeric', maxLength: null },
      { name: 'EINHEIT', type: 'string', maxLength: 50 },
      { name: 'STK_BR', type: 'numeric', maxLength: null },
    ],
  },
  {
    file: 'itemamounts.csv',
    tableName: 'Bonpos_Preisfindung',
    columns: [
      { name: 'Z_KASSE_ID', type: 'string', maxLength: 50 },
      { name: 'Z_ERSTELLUNG', type: 'string', maxLength: 30 },
      { name: 'Z_NR', type: 'numeric', maxLength: null },
      { name: 'BON_ID', type: 'string', maxLength: 40 },
      { name: 'POS_ZEILE', type: 'string', maxLength: 50 },
      { name: 'TYP', type: 'string', maxLength: 20 },
      { name: 'UST_SCHLUESSEL', type: 'numeric', maxLength: null },
      { name: 'PF_BRUTTO', type: 'numeric', maxLength: null },
      { name: 'PF_NETTO', type: 'numeric', maxLength: null },
      { name: 'PF_UST', type: 'numeric', maxLength: null },
    ],
  },
  {
    file: 'subitems.csv',
    tableName: 'Bonpos_Zusatzinfo',
    columns: [
      { name: 'Z_KASSE_ID', type: 'string', maxLength: 50 },
      { name: 'Z_ERSTELLUNG', type: 'string', maxLength: 30 },
      { name: 'Z_NR', type: 'numeric', maxLength: null },
      { name: 'BON_ID', type: 'string', maxLength: 40 },
      { name: 'POS_ZEILE', type: 'string', maxLength: 50 },
      { name: 'ZI_ART_NR', type: 'string', maxLength: 50 },
      { name: 'ZI_GTIN', type: 'string', maxLength: 50 },
      { name: 'ZI_NAME', type: 'string', maxLength: 60 },
      { name: 'ZI_WARENGR_ID', type: 'string', maxLength: 40 },
      { name: 'ZI_WARENGR', type: 'string', maxLength: 50 },
      { name: 'ZI_MENGE', type: 'numeric', maxLength: null },
      { name: 'ZI_FAKTOR', type: 'numeric', maxLength: null },
      { name: 'ZI_EINHEIT', type: 'string', maxLength: 50 },
      { name: 'ZI_UST_SCHLUESSEL', type: 'numeric', maxLength: null },
      { name: 'ZI_BASISPREIS_BRUTTO', type: 'numeric', maxLength: null },
      { name: 'ZI_BASISPREIS_NETTO', type: 'numeric', maxLength: null },
      { name: 'ZI_BASISPREIS_UST', type: 'numeric', maxLength: null },
    ],
  },
  {
    file: 'transactions_tse.csv',
    tableName: 'TSE_Transaktionen',
    columns: [
      { name: 'Z_KASSE_ID', type: 'string', maxLength: 50 },
      { name: 'Z_ERSTELLUNG', type: 'string', maxLength: 30 },
      { name: 'Z_NR', type: 'numeric', maxLength: null },
      { name: 'BON_ID', type: 'string', maxLength: 40 },
      { name: 'TSE_ID', type: 'numeric', maxLength: null },
      { name: 'TSE_TANR', type: 'numeric', maxLength: null },
      { name: 'TSE_TA_START', type: 'string', maxLength: 30 },
      { name: 'TSE_TA_ENDE', type: 'string', maxLength: 30 },
      { name: 'TSE_TA_VORGANGSART', type: 'string', maxLength: 30 },
      { name: 'TSE_TA_SIGZ', type: 'numeric', maxLength: null },
      { name: 'TSE_TA_SIG', type: 'string', maxLength: 512 },
      { name: 'TSE_TA_FEHLER', type: 'string', maxLength: 200 },
      { name: 'TSE_VORGANGSDATEN', type: 'string', maxLength: 1000 },
    ],
  },
  {
    file: 'transactions_vat.csv',
    tableName: 'Bonkopf_USt',
    columns: [
      { name: 'Z_KASSE_ID', type: 'string', maxLength: 50 },
      { name: 'Z_ERSTELLUNG', type: 'string', maxLength: 30 },
      { name: 'Z_NR', type: 'numeric', maxLength: null },
      { name: 'BON_ID', type: 'string', maxLength: 40 },
      { name: 'UST_SCHLUESSEL', type: 'numeric', maxLength: null },
      { name: 'BON_BRUTTO', type: 'numeric', maxLength: null },
      { name: 'BON_NETTO', type: 'numeric', maxLength: null },
      { name: 'BON_UST', type: 'numeric', maxLength: null },
    ],
  },
  {
    file: 'lines_vat.csv',
    tableName: 'Bonpos_USt',
    columns: [
      { name: 'Z_KASSE_ID', type: 'string', maxLength: 50 },
      { name: 'Z_ERSTELLUNG', type: 'string', maxLength: 30 },
      { name: 'Z_NR', type: 'numeric', maxLength: null },
      { name: 'BON_ID', type: 'string', maxLength: 40 },
      { name: 'POS_ZEILE', type: 'string', maxLength: 50 },
      { name: 'UST_SCHLUESSEL', type: 'numeric', maxLength: null },
      { name: 'POS_BRUTTO', type: 'numeric', maxLength: null },
      { name: 'POS_NETTO', type: 'numeric', maxLength: null },
      { name: 'POS_UST', type: 'numeric', maxLength: null },
    ],
  },
  {
    file: 'allocation_groups.csv',
    tableName: 'Bonkopf_AbrKreis',
    columns: [
      { name: 'Z_KASSE_ID', type: 'string', maxLength: 50 },
      { name: 'Z_ERSTELLUNG', type: 'string', maxLength: 30 },
      { name: 'Z_NR', type: 'numeric', maxLength: null },
      { name: 'BON_ID', type: 'string', maxLength: 40 },
      { name: 'ABRECHNUNGSKREIS', type: 'string', maxLength: 50 },
    ],
  },
  {
    file: 'references.csv',
    tableName: 'Bon_Referenzen',
    columns: [
      { name: 'Z_KASSE_ID', type: 'string', maxLength: 50 },
      { name: 'Z_ERSTELLUNG', type: 'string', maxLength: 30 },
      { name: 'Z_NR', type: 'numeric', maxLength: null },
      { name: 'BON_ID', type: 'string', maxLength: 40 },
      { name: 'POS_ZEILE', type: 'string', maxLength: 50 },
      { name: 'REF_TYP', type: 'string', maxLength: 20 },
      { name: 'REF_NAME', type: 'string', maxLength: 40 },
      { name: 'REF_DATUM', type: 'string', maxLength: 30 },
      { name: 'REF_Z_KASSE_ID', type: 'string', maxLength: 50 },
      { name: 'REF_Z_NR', type: 'numeric', maxLength: null },
      { name: 'REF_BON_ID', type: 'string', maxLength: 40 },
    ],
  },
];

export function dsfinvkTable(file: string): DsfinvkTable {
  const table = DSFINVK_SCHEMA.find((t) => t.file === file);
  if (!table) throw new Error(`Unknown DSFinV-K table: ${file}`);
  return table;
}
